name: ng2_dragula
version: 0.0.2
description: Drag and drop component for Angular 2 Dart.
author: Kasper Peulen <kasperpeulen@gmail.com>
homepage: https://github.com/kasperpeulen/ng2-dragula.git
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular: ^4.0.0
  dragula: ^0.1.1
  js: ^0.6.1
dev_dependencies:
  dart_to_js_script_rewriter: ^1.0.1
  browser: ^0.10.0
transformers:
  - angular:
      entry_points:
        - web/main.dart
  - dart_to_js_script_rewriter